### ISSUE TITLE
Error while launching the game 

### ISSUE THREAD

**Issue by PakuDrag** [kassindornelles/lol-for-linux-installer#16]
No problem with installation and the game worked the first time after install but when I try to open the launch py script (launch-league-of-legends.py) I get this error. 

import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.

import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.

./games/Lol/launch-league-of-legends.py: line 3: syntax error near unexpected token `('

./games/Lol/launch-league-of-legends.py: line 3: `home_dir = os.path.expanduser('/home/paku')'

(Without the gaps)

**Comment by kassindornelles** [comment]
Should be fixed by: https://github.com/kassindornelles/lol-for-linux-installer/commit/31d23b4fa55f93d1086a32061d86ac31a4b69793

try this release:
https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v1.1.1

**Comment by PakuDrag** [comment]
Trying now

**Comment by kassindornelles** [comment]
awesome!

**Comment by PakuDrag** [comment]
Thanks to you!!
