### ISSUE TITLE
Can't launch the python script

### ISSUE THREAD

**Issue by gbreuil** [kassindornelles/lol-for-linux-installer#17]
![Screenshot_20230328_195033](https://user-images.githubusercontent.com/26203411/228325774-8b3670e2-3b10-4f19-b1ab-0ae83142ef47.png)

Seems a syntax error is in the script i don't know why, when i remove the line it's still the same.
First time installing works because the game launches but when you try the second time the script get the error.

**Comment by kassindornelles** [comment]
Should be fixed by: https://github.com/kassindornelles/lol-for-linux-installer/commit/31d23b4fa55f93d1086a32061d86ac31a4b69793

try this release:
https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v1.1.1

**Comment by gbreuil** [comment]
nevermind saw the other post adding `#!/usr/bin/env python3` works
