### ISSUE TITLE
It doesn't open

### ISSUE THREAD

**Issue by mvosgnach** [kassindornelles/lol-for-linux-installer#21]
Hello!
I'm trying to install via python script but when I double click, it doesn't open. I've tried clicking "run" and "run in terminal".
![Screenshot from 2023-03-30 11-22-43](https://user-images.githubusercontent.com/13545595/228867396-9af8d044-c7ae-40ee-83b1-2ef85315021b.png)

I already installed the dependencies, I'm using Zorin OS and I have an AMD RX 480.

**Comment by PakuDrag** [comment]
Can you run through terminal manually  to see the error message? like
` python3 /path/to/installer`

**Comment by mvosgnach** [comment]
I'll try later. I installed via bash though, it worked.

**Comment by kassindornelles** [comment]
We made a new release, can you try that?

**Comment by mvosgnach** [comment]
I found that python-requests, qt5-base and pyqt5 (Python script) are not working, apparently. For example, in the terminal "$ sudo apt-get install pyqt5 " installs it but after that, it can't be located. Am I doing something wrong?
![Screenshot from 2023-03-31 14-58-08](https://user-images.githubusercontent.com/13545595/229195906-0f5455af-056c-469b-b501-1a5eb4cd6343.png)

**Comment by kassindornelles** [comment]
You are missing dependencies but I'm not sure how Qt is distributed on Ubuntu based distros, I'll investigate it.

**Comment by kassindornelles** [comment]
Not our bug, seems like you need to figure out what the dependencies are on your distro
