### ISSUE TITLE
Some missing features

### ISSUE THREAD

**Issue by EndChapter** [kassindornelles/lol-for-linux-installer#23]
Ok, good work! But you forgot to say that we need to close the client after installation is finished. It also installs 7-Zip and Firefox in the wine version for no reason. Also It will be good if we can change winecfg(Since it dont run in flatpak i need to restrict to home access for lol). Behind that, thank you for making this!

**Comment by kassindornelles** [comment]
> Ok, good work! But you forgot to say that we need to close the client after installation is finished. It also installs 7-Zip and Firefox in the wine version for no reason. Also It will be good if we can change winecfg(Since it dont run in flatpak i need to restrict to home access for lol). Behind that, thank you for making this!

You don't need to close the client after install is done, you can start playing right away, my installer should close itself
And you are sure that Firefox is being installed? Sometimes winetricks gets drunk and says it is installing Firefox but it actually isn't, is just a bug (at least for me it never really installed Firefox in the prefix but it said that it did)

**Comment by EndChapter** [comment]
I tried without closing client in the first place, it didnt work after 2nd startup. I think it is wine-ge's patch. About firefox I jus read a lot of messages about firefox but I dont see one its true. Also I cant run with dGPU rn I am looking for a workaround for myself.

**Comment by kassindornelles** [comment]
you normally use DRI_PRIME=1 to use the dGPU?

**Comment by kassindornelles** [comment]
Try this, edit the launch league script and add the line like i did, if that fixes it i might add a option for prime users
`DRI_PRIME="1",`
![Screenshot_20230402_072609](https://user-images.githubusercontent.com/40970965/229347348-f222bdd2-f079-481f-a896-8f7e51b04dfc.png)

**Comment by kassindornelles** [comment]
i made a branch that has the dGPU option, i would like some testing
https://github.com/kassindornelles/lol-for-linux-installer/tree/hybridgraphics-option

**Comment by kassindornelles** [comment]
> I tried without closing client in the first place, it didnt work after 2nd startup. I think it is wine-ge's patch. About firefox I just read a lot of messages about firefox but I dont see one its true. Also I cant run with dGPU rn I am looking for a workaround for myself.

it makes no sense that is not working, are you sure you have all the dependencies installed? 99% of the people reporting issues didnt check the dependencies part of the readme of the project and then stuff breaks

**Comment by EndChapter** [comment]
> it makes no sense that is not working, are you sure you have all the dependencies installed? 
I played 5 games today (Without dGPU) after closing client.(I reinstalled and closed client after login and it worked), and yes I checked all deps while installing game.
About dGPU with  DRI_PRIME="1": 
```fsync: up and running.
wine: Unhandled page fault on execute access to XXXXXXXXXXXXXXXX at address XXXXXXXXXXXXXXXX (thread XXXX), starting debugger...
wine: Unhandled page fault on execute access to XXXXXXXXXXXXXXXX at address XXXXXXXXXXXXXXXX (thread XXXX), starting debugger...```
Exact same error while installing game on Lutris. I think it is not about your script. It is about nvidia or wine's itself.
I also tried with `__NV_PRIME_RENDER_OFFLOAD="1"` `__GLX_VENDOR_LIBRARY_NAME="nvidia"` without `DRI_PRIME="1"` it opens login client but quits while opening real client.

**Comment by kassindornelles** [comment]
> > it makes no sense that is not working, are you sure you have all the dependencies installed?
> 
> I played 5 games today (Without dGPU) after closing client.(I reinstalled and closed client after login and it worked), and yes I checked all dependencies while installing game. About dGPU with `DRI_PRIME="1"`: `fsync: up and running. wine: Unhandled page fault on execute access to XXXXXXXXXXXXXXXX at address XXXXXXXXXXXXXXXX (thread XXXX), starting debugger... wine: Unhandled page fault on execute access to XXXXXXXXXXXXXXXX at address XXXXXXXXXXXXXXXX (thread XXXX), starting debugger...`
> 
> Exact same error while installing game on Lutris. I think it is not about your script. It is about nvidia or wine's itself. I also tried with `__NV_PRIME_RENDER_OFFLOAD="1"` `__GLX_VENDOR_LIBRARY_NAME="nvidia"` without `DRI_PRIME="1"` it opens login client but quits while opening real client. I also tried reinstalling with offload(I have good internet connection :D). It also closes while opening real client.(Edit: for the records I tried reinstalling with `DRI_PRIME="1"` too it also doesn't worked)(I also tried with `gamemoderun` no changes for nvidia)

ok so i'm kinda confused, what is this issue about anyway?
i kinda lost track, sorry

**Comment by EndChapter** [comment]
Winecfg feature

**Comment by kassindornelles** [comment]
you want to be able to launch winecfg to mess around?

**Comment by kassindornelles** [comment]
i figured that DRI_PRIME=1 will not fix your issue, the variables needed are 
NV_PRIME_RENDER_OFFLOAD=1 VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
will need to make some changes

**Comment by EndChapter** [comment]
Bro, if you read that what I wrote you will see I already tried passtrough(with 2 and 3 params you dont even will to help thanks for helping I close the issue since I found winecfg in bin folder.)

**Comment by kassindornelles** [comment]
deleted your last comment since you need to learn to be respectful to people that are trying to help you

you failed to explain your problem and also added others on top of it

you asked for meme features like winecfg when the entire point of this script is just to setup wine-ge-lol and launch it without having to rely in a full game launcher

i dont use nvidia hardware, i dont feel like supporting people on nvidia hybrid graphics and will close all issues related to nvidia for now thanks to you
