### ISSUE TITLE
GPU utilization

### ISSUE THREAD

**Issue by silasmue** [kassindornelles/lol-for-linux-installer#25]
My dedicated GPU doesnt get used ingame, despite of beeing selected in the install wizard. I am not sure if this is a problem with, Wine, Vulcan or the NVIDIA driver.

Using a RTX 2070 with 530 drivers.
Vulkan works on other games (Victoria3 over steam).
Do you have any suggestions for me to test and fix this without reistallation? 

I think it is using lavapipe to render, because CPU usage is very high when executing the game.

vulkaninfo shows the NVIDIA card as GPU 0 and llvmpipe as GPU 1

**Comment by kassindornelles** [comment]
> My dedicated GPU doesnt get used ingame, despite of beeing selected in the install wizard. I am not sure if this is a problem with, Wine, Vulcan or the NVIDIA driver.
> 
> Using a RTX 2070 with 530 drivers. Vulkan works on other games (Victoria3 over steam). Do you have any suggestions for me to test and fix this without reistallation?
> 
> I think it is using lavapipe to render, because CPU usage is very high when executing the game.
> 
> vulkaninfo shows the NVIDIA card as GPU 0 and llvmpipe as GPU 1

right now we dont support nvidia hybrid graphics, and to be fair i dont want to support it either because i dont have such hardware to test if stuff is actually working :/

**Comment by kassindornelles** [comment]
check the launch-league-of-legends.py file, there should be a line like `DRI_PRIME="0"`
change the value to 1, i have no idea if NV hybrid graphics recognize PRIME at all, i'm seriously completely ignorant about it sorry :(

**Comment by silasmue** [comment]
Okay I am trying to fix it myself, because it should be possible. Are the ENVVARIABLES everything that is exported or does the wine configuration do something else?
Do you know where I can find the configuration of DXVK? I am not very experienced with wine, but that seems kinda fun and I dont want to do a single GPU passthrough if possible...

**Comment by silasmue** [comment]
I mean the environment variables in the launch-league-of-legends.py to be clear.

**Comment by silasmue** [comment]
Until now I discoverd that the problem is somehow DXVK, because Vulkan isnt even starting and Wine3d doesnt find the nvidia GPU. Not sure if setting VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia.[x86_64].json is doing the trick, because after that the client crashes after login because missing NVML_auth (winbinding in wine). DRI_PRIME for NVIDIA is __NV_PRIME_RENDER_OFFLOAD=1 (https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html).

If I discover a fix I post it.

**Comment by silasmue** [comment]
It works with PopOS without any tweaks. I am not sure if the problem was something in Fedora for example some weird packaging stuff or falsly installed or bad nvidia drivers.
I think the problem is nvidia related but I am not sure because other games worked fine, maybe some weird misconfiguration or something else.

I can verify that LoL works with RTX 2070 and driver version 525.89.02 on PopOS 22.04 LTS with X11 at capped 240 fps in practise tool.

The game looks perfekt and feels about 95% perfekt. Maybe I can hit diamond on linux would be cool...

Thank you for your work. Because Lutris didn't work for some reason...
