### ISSUE TITLE
No shortcut created and no executable file found in installation directory

### ISSUE THREAD

**Issue by OC-VORTEKS** [kassindornelles/lol-for-linux-installer#28]
After installing to a separate drive, this is all that is found in the installation directory, there is no file that I can find to open the league client:
![Screenshot_20230412_091752](https://user-images.githubusercontent.com/52713404/231503654-8997773f-0564-4279-b090-c0b9f02a22ba.png)
and there is no shortcut found anywhere.

**Comment by kassindornelles** [comment]
Need the following info:
Distribution name
Installer script used (Python or Bash)
Version of the script in use
And i also need to know if you installed all the dependencies

**Comment by OC-VORTEKS** [comment]
Distro: Kubuntu 22.04
Installer script: Python
Version: 1.2.3
I have double checked and confirmed that all of the dependencies have been installed

**Comment by kassindornelles** [comment]
tried in a VM and i cannot reproduce your problem, try to make a clean install of league

**Comment by kassindornelles** [comment]
@OC-VORTEKS can you try our latest release? thanks!
https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v1.3.1

**Comment by OC-VORTEKS** [comment]
Okay, I just cleared out the installation and, downloaded the 1.3.1 file, and got the exact same result. This time, I ran it with terminal and got this error (which looks like it might just be a consequence of installing it on an external hard drive):
![Screenshot_20230414_155120](https://user-images.githubusercontent.com/52713404/232161059-e5747d5c-055e-4372-aa49-3e4dbe50b006.png)

**Comment by kassindornelles** [comment]
thats some interesting info, will investigate that %appdata% error message :ok_hand:

**Comment by kassindornelles** [comment]
oh wait, you are running it in a NTFS partition?

**Comment by kassindornelles** [comment]
might be worth trying to chmod it:
 `chmod +x "Install League of Legends (Python).py"`

**Comment by OC-VORTEKS** [comment]
Okay, chmod didn't work, so I ended up just installing it to the /.local/share/leagueoflegends/ directory, which worked out fine. I would personally recommend adding the option to either install the game to that directory as default, or customizing the install location, since you can't navigate to that location within the python script since the /.local/ directory is hidden and must be copied to the installer manually. Thank you for your help!

**Comment by kassindornelles** [comment]
> Okay, chmod didn't work, so I ended up just installing it to the /.local/share/leagueoflegends/ directory, which worked out fine. I would personally recommend adding the option to either install the game to that directory as default, or customizing the install location, since you can't navigate to that location within the python script since the /.local/ directory is hidden and must be copied to the installer manually. Thank you for your help!

i guess i'm gonna limit it to the home folder only, thanks for your testing!

**Comment by OC-VORTEKS** [comment]
No problem!
