### ISSUE TITLE
[Suggestion] Add update script

### ISSUE THREAD

**Issue by Gold3nF3nix** [kassindornelles/lol-for-linux-installer#29]
Make update script for available users to update to the new wine version

**Comment by kassindornelles** [comment]
@polkaulfield any ideas in how we should do it?
i had an idea to download and read this json file https://github.com/kassindornelles/lol-for-linux-installer/blob/main/wine_build.json and compare to another .json file we would create in the install folder and if the value is different download the new build and extract it to the wine-build folder

**Comment by kassindornelles** [comment]
or maybe we should we do it in launch-league-etc.py script

**Comment by kassindornelles** [comment]
We have a update script in place that only works to get newer WINE builds for now, it is copied to the game folder at install time.
https://github.com/kassindornelles/lol-for-linux-installer/blob/main/python_src/src/update.py

**Comment by eddebc** [comment]
Experimenting with wine builds [can lead](https://www.reddit.com/r/leagueoflinux/comments/12cei7t/patch_137_feedback_megathread_transition_to_64bit/) to a broken env, such as my case.  
  
* Update start
* Move game dir, if found
* Download wine
* Configure prefix
* Move game dir back or install
* Create/overwrite shortcuts

This'll also enable reusing installation script functions once that long function is refactored into smaller ones.
