### ISSUE TITLE
Game doens't start

### ISSUE THREAD

**Issue by ashurffw** [kassindornelles/lol-for-linux-installer#30]
**Describe the bug**
The game does not start, it opens and closes a black screen and stays in the "reconnect" part of the client.
And also very low FPS in client, in lobby for normal game it would take a while to make the runes.
![league](https://user-images.githubusercontent.com/103474624/231576275-d6009902-027c-4514-8915-18454f871ad3.png)

**Are you sure you installed ALL the dependencies listed in the readme?**
- [ ] Yes
- [X] Not sure

**To Reproduce**
1 -  Open Client and login
2 - "Play" button
3 - Training, Training mode
4 - Pick a champion and game not start
**Describe your problem as detailed as possible**
The game just won't start, and have a LOW FPS in client

**Screenshots**

**Desktop (please complete the following information):**
 - Linux Distribution: backbox OS
 - Version of the installer:1.2.3

**Additional context**
I have installed wine-lutris 7.0.8

**Comment by kassindornelles** [comment]
what is the GPU you are using?

**Comment by ashurffw** [comment]
I installed full dependencias now, but not start the game. I using a RX 550

**Comment by kassindornelles** [comment]
> I installed full dependencias now, but not start the game. I using a RX 550

can you go to the game folder, open a terminal/console in that folder and run the "launch-league-of-legends.py" script on it then try to get in training mode again?

maybe the terminal information will give us a clue on what is happening

**Comment by ashurffw** [comment]
Cara a gente pode falar em português? or pref english
Traceback (most recent call last):
  File "/home/ashurffw/lolzada/launch-league-of-legends.py", line 20, in <module>
    subprocess.run(wine_process, env=start_game_vars, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
I did what you asked and relented that

**Comment by kassindornelles** [comment]
esses arquivos e pastas tudo existem pra ti? 
pelo jeito ele não ta achando o executavel do wine

![Screenshot_20230412_191621](https://user-images.githubusercontent.com/40970965/231598179-c8998c05-2b1a-45be-9acd-c307376176dc.png)

**Comment by kassindornelles** [comment]
na verdade isso ta bizarro, se não tivesse encontrando o executavel do WINE ele nem abriria o client do lol

**Comment by kassindornelles** [comment]
esse teu backbox OS ai é baseado em qual ubuntu? 22.04?

**Comment by ashurffw** [comment]
Cara agora ele nao ta abrindo o client do lol, reiniciei o pc e ele nao abre mais. E existe sim, não sei qual versao do ubuntu mas deve ser 22.04 pq lançou em 15/11 de 2022 e o ubuntu 22.04 lançou no começo de 22
![image](https://user-images.githubusercontent.com/103474624/231604848-0de1eeda-c9f5-49ec-b74f-cb26cf77de84.png)

**Comment by kassindornelles** [comment]
vou instalar essa distro numa maquina virtual pra ver no que da

**Comment by kassindornelles** [comment]
tenta instalar os pacote do samba e winbind

`sudo apt install samba winbind`

**Comment by ashurffw** [comment]
Cara, não queria desinstalar e só abria e fechava o Terminal então rodei pelo vscode e deu isso;
Failed to read JSON file: [Errno 2] No such file or directory: '/home/ashurffw/.config/league_install_path.json'
^CTraceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ashurffw/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/ashurffw/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/ashurffw/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/ashurffw/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ashurffw/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ashurffw/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/ashurffw/lolzada/uninstall.py", line 27, in <module>
    shutil.rmtree(game_main_dir)
NameError: name 'game_main_dir' is not defined

**Comment by kassindornelles** [comment]
Distro baseada no Ubuntu é muito meme, só dá problema 
Nada desse log aí diz algo de valor

 o q tu pode tentar é o script em Bash mesmo, aqui na minha máquina virtual ele criou todos os arquivos direitinho e inclusive desinstalou com sucesso tb :/

**Comment by ashurffw** [comment]
Eu vou tentar instalar por Bash, mas tem como desinstalar pelo Bash também? Ou só instalo uma por cima da outra? E tu tem razão, peguei esse backbox pq eu tava sem pendrive e um amigo me emprestou pra formatar. Mas to a horas pra ir pro BlackArch

**Comment by ashurffw** [comment]
Solucionei o problema, jogo ta abrindo e diminuiu o Lag instalando por Bash. If an greengo have the same problem install for bash, i don't uninstalled, only runned the bash archive and works 100%

**Comment by ashurffw** [comment]
PoRRA eu reiniciei meu pc e nao ta abrindo dnv ....          $@SXXZCVDFasolsdfkospdfk

**Comment by kassindornelles** [comment]
> PoRRA eu reiniciei meu pc e nao ta abrindo dnv .... $@SXXZCVDFasolsdfkospdfk

rapaz mete o EndeavorOS ai q é baseado no arch q resolve na hora uahsuahsuas
mas to testando uma build nova do WINE aq pra ver se resolve teu problema

**Comment by kassindornelles** [comment]
> PoRRA eu reiniciei meu pc e nao ta abrindo dnv .... $@SXXZCVDFasolsdfkospdfk

tu por acaso troca a pasta de lugar depois q instala o jogo? pq o script é bem limitado, trocou ele de caminho ele se quebra todo, tem q usar aquele caminho especifico q tu escolheu na hora de instalar o jogo

**Comment by ashurffw** [comment]
Mano, sim. Mas agora eu não consigo desinstalar pq eu ja fui no ./local/share e nao tem aplications KKKKKKKKKKKKKKKKKKKKKKKKK q inferno viado pqp, eu formatei o pc e coloquei outra distro e fiz msm cagada

**Comment by ashurffw** [comment]
Tipo, ele instala e pá, da pra jogar, ai eu fecho e ele nao abre mais, só aparece a riot games e fecha

**Comment by kassindornelles** [comment]
manda um print do teu arquivo "launch-league-of-legends.py" num editor de texto

**Comment by kassindornelles** [comment]
na real tenta esse appimage aqui:
https://github.com/polkaulfield/lol-for-linux-installer/releases/download/appimage/LoL-for-Linux-Installer-1.2.4-x86_64.AppImage

é de um contribuidor nosso então é seguro eu mesmo ja testei e usei

**Comment by ashurffw** [comment]
HAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAAHAHAHAHAA Não foi denovo, instalei por cima dali e nao mudei a pasta que ele escolheu, e nao abre.

#!/usr/bin/env python3
import os
import subprocess
home_dir = os.path.expanduser('/home/ashurffw/')
game_main_dir = os.path.join('/home/ashurffw/Downloads')
game_main_wine_dir = os.path.join(game_main_dir, 'wine')
game_prefix_dir = os.path.join(game_main_wine_dir, 'prefix')
game_exe_path = os.path.join(game_prefix_dir, 'drive_c', 'Riot Games', 'Riot Client')
game_exe_file_name = 'RiotClientServices.exe'
start_game_vars = dict(os.environ,
       PATH='/home/ashurffw/Downloads/wine/lutris-ge-lol-7.0.8-x86_64/bin',
        WINEPREFIX=game_prefix_dir,
       WINELOADER="/home/ashurffw/Downloads/wine/lutris-ge-lol-7.0.8-x86_64/bin/wine",
        WINEFSYNC="1",
        WINEDEBUG="-all",
        WINEDLLOVERRIDES="winemenubuilder.exe=d",
    )
wine_process = ["wine", os.path.join(game_exe_path, game_exe_file_name), "--launch-product=league_of_legends", "--launch-patchline=live"]
subprocess.run(wine_process, env=start_game_vars, check=True)
![image](https://user-images.githubusercontent.com/103474624/232088558-18d43067-39e7-4dff-94ae-5d581565c0fe.png)

**Comment by kassindornelles** [comment]
perai to fazendo uma mudança braba aqui no launch-league script, quando tiver pronto tentamos de novo

**Comment by kassindornelles** [comment]
Baixa essa release aqui e tenta de novo:
https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v1.3

Se não funcionar agora eu desisto real oficial

**Comment by ashurffw** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK DESISTO VIADO PPRT, mas ta certo, eu instalo e reinstalo td vez que eu for jogar n tem problema valeu mano pelo tempo gasto <3

**Comment by kassindornelles** [comment]
> KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK DESISTO VIADO PPRT, mas ta certo, eu instalo e reinstalo td vez que eu for jogar n tem problema valeu mano pelo tempo gasto <3

ta doido faz isso não, tenta usar o Lutris cara
o lutris tem um instaladorzinho pro LoL
