### ISSUE TITLE
[Bug] launch-league-of-legends-prime.py SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by Naplifayaie** [kassindornelles/lol-for-linux-installer#36]
Hello, I found an issue in one of your scripts:

launch-league-of-legends-prime.py 

Line 18 should be with a comma, not a period 
```
WINEESYNC="1".
WINEESYNC="1",
```

I got the error on fedora 38, latest release of lol-for-linux-installer with the following error:

```
[naplifayaie@fedora League of Legends]$ ./launch-league-of-legends.py 
  File "/home/naplifayaie/League of Legends/./launch-league-of-legends.py", line 19
    WINEFSYNC="1",
             ^
SyntaxError: invalid syntax
```

**Comment by kassindornelles** [comment]
I recommend to backup your riot games folder in the prefix folder and try the latest release
https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/2.0

**Comment by kassindornelles** [comment]
updated my comment with a new release, simply copy all the files of the release above to your game folder and replace the old files.

**Comment by kassindornelles** [comment]
should be fixed upstream
