### ISSUE TITLE
[Bug] 2.0 makes my CPU run at 70°C+

### ISSUE THREAD

**Issue by Kagukara** [kassindornelles/lol-for-linux-installer#37]
**Describe the bug**
The new installer/launcher v2.0 causes my CPU to run 70°C+. LeagueClientUxR using 95%+ on CPU.

**Are you sure you installed ALL the dependencies listed in the readme?**
- [x] Yes
- [ ] Not sure

**To Reproduce**
1 - Download latest installer (2.0)
2 - Extract file
3 - Run launch-league-of-legends.py inside the folder you extracted
4 - Next → Region Select (EUW) → Next → Keep "Create desktop shortcut enabled and Use dedicated GPU (DRI_PRIME=1) unchecked (doesn't solve issue if checked) → Install League of Legends → Create Installation Folder
5 - Click install when popup appears
6 - Wait for League Client to finish installing then exit
7 - Launch League via the menu shortcut (Desktop Shortcut)
8 - Select Renderer DXVK 2.1 or 1.10.3 (doesn't matter which one client still makes cpu 70°C+)
9 - Check for WINE updates → Apply Changes → Start League of Legends
10 - Login → Let league install
11 - Turn on Enable Low Spec Mode and Close client during game to Always
12 - Go to Profile (not much going on so its best to check here) and wait for League to finish downloading

**Describe your problem as detailed as possible**
I expect the client to not cause my CPU to run 70°C+. v1.5 did not cause this issue, even while updating it didn't get as hot as v2.0.

**Screenshots**
lol-for-linux-installer 2.0
![capture_2023-04-29_13-25-38](https://user-images.githubusercontent.com/43391109/235302524-45d06781-0505-4f51-99a6-faadb80ca46b.png)

lol-for-linux-installer v1.5
![capture_2023-04-29_13-49-47](https://user-images.githubusercontent.com/43391109/235303329-553fcad3-afc2-456f-8180-869d2d1672f7.png)

**Desktop (please complete the following information):**
 - Linux Distribution: Arch Linux
 - Version of the installer: 2.0

**Additional context**
OS: Arch Linux
KERNEL: 6.2.12-arch1-1
WM: sway (sway version 1.8.1)
CPU: AMD Ryzen 9 5950X 16-Core
GPU: AMD Radeon RX 7900 XTX (gfx1100, LLVM 16.0.0, DRM 3.49, 6.2.12-arch1-1)
GPU DRIVER: 4.6 Mesa 23.1.0-devel (git-7fe469d6c8)
RAM: 64 GB

**Comment by kassindornelles** [comment]
i think that might be because we are failing to install DXVK, i'm working in a solution

**Comment by kassindornelles** [comment]
ok, i figured a fix, will land soon on main branch, you wont have to reinstall to fix it (will have to copy some new files to the game folder tho...)

**Comment by Kagukara** [comment]
Great, will try it out when on main branch.

**Comment by kassindornelles** [comment]
Ok, is done

1 - Download the main branch: https://github.com/kassindornelles/lol-for-linux-installer/archive/refs/heads/main.zip
2 - Extract the files and copy the files `env_vars.json` and `launch-league-of-legends.py` to your game install folder, replacing the old files
3 - Launch the league manager normally and install DXVK:
![Screenshot_20230429_195857](https://user-images.githubusercontent.com/40970965/235327447-27b75140-7973-49cf-b7d7-730b4ec2c2d7.png)

**Comment by kassindornelles** [comment]
Made a hotfix release:
https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v2.0.1

**Comment by kassindornelles** [comment]
I'm not entirely sure if the client uses DirectX for rendering, but it if does it should in theory fix it

**Comment by Kagukara** [comment]
Clicking apply changes causes it to close instantly.

**Comment by kassindornelles** [comment]
oh, give me a second, that was a dumb mistake oof

**Comment by kassindornelles** [comment]
[launch-league-of-legends.tar.gz](https://github.com/kassindornelles/lol-for-linux-installer/files/11360212/launch-league-of-legends.tar.gz)
here

**Comment by kassindornelles** [comment]
will fix-the-hotfix release in a second (lol)

**Comment by Kagukara** [comment]
Seems to be fixed now, thank you. Which DXVK version is recommended 1.10.3 or 2.1?

**Comment by kassindornelles** [comment]
for your GPU 2.1 is recommended, yes

**Comment by kassindornelles** [comment]
for older GPU's 1.10.3 is the best option for compat.
