### ISSUE TITLE
[Question] Vulkan support is required to use the installer?

### ISSUE THREAD

**Issue by Vilianexe** [kassindornelles/lol-for-linux-installer#38]
In the main page it showed about DXVK support, but my gpu don't support vulkan(too old) so i was thinking if i can use your launcher without vulkan
Thank you for helping the community!

**Comment by kassindornelles** [comment]
> In the main page it showed about DXVK support, but my gpu don't support vulkan(too old) so i was thinking if i can use your launcher without vulkan Thank you for helping the community!

by default we dont install dxvk, so you will run the game using wined3d opengl renderer, try training mode to see if it will work for you
