### ISSUE TITLE
[Question]  Two questions (bug + gamescope)

### ISSUE THREAD

**Issue by hoony0203** [kassindornelles/lol-for-linux-installer#39]
Thank you for your work. Seek of tired install and playing Lol in wayland, I found your installer (-;

I am noob for linux (just start linux for one month), but if you give me some advice then I'll found and try myself solve my problems.

Testing At

- archlinux + kde wayland   // archlinux + sway
- nvidia (3060 laptop / 3070ti discrete ) + proprietary driver
- wine : Lutris-GE-7.0-8-LoL
- multi monitor (120hz + 75hz)

1) Stuck at loading (after champ select)
About 50% or 75% load and stop. 
Lutris and this launcher was same. 
Disable vrr and Use single monitor doesn't  work.
Program crash and shown reconnect button. If reconnect then Screen stuck at yellow pause phase. 

2) How can apply gamescope to this program?

I found archwiki, add desktop exec command line could be work 
but lauch-script.py was independently(?) make his path and commandline. 
Is it possible add gamescope command line that py? or Just add gamescope command to "league of legends.desktop"

**Comment by kassindornelles** [comment]
The first bug, did you try messing around different DXVK versions?

The gamescope thing: in the main branch i added gamescope support but right now is really basic, you can't set resolution and FSR or anything else really.

Will work on expanding its functionality, not sure when all the work will be completed tho.

**Comment by kassindornelles** [comment]
I made a gamescope implementation but it is failing to grab the keyboard and mouse input, not sure why
