### ISSUE TITLE
[Suggestion] Add obs-vkcapture

### ISSUE THREAD

**Issue by Kagukara** [kassindornelles/lol-for-linux-installer#41]
Would it be possible to have an option in the launcher to enable `obs-gamecapture %command%` from https://github.com/nowrep/obs-vkcapture?

**Comment by kassindornelles** [comment]
Sure, after I did a gigantic gamescope implementation that doesn't works because of a upstream bug I can't add all sorts of bloat lol

**Comment by kassindornelles** [comment]
@Kagukara do you even know if the obs-gamecapture actually works on lol?
i dont want to add one more thing that doesnt works

**Comment by Kagukara** [comment]
I can confirm it works. I re-downloaded lol-for-linux-installer v1.5 and set in the .desktop file for `Exec`, `Exec=obs-gamecapture mangohud %command% python3 launch-league-of-legends.py`. Which enables obs-vkcapture.

Screenshot of it working:
![screenshot_2023-05-08_20-57-36](https://user-images.githubusercontent.com/43391109/236921983-4b7aa2b7-2b6c-4073-8932-69c7d1ceca7b.png)

**Comment by kassindornelles** [comment]
Download the main branch, extract the files and copy: `launch-league-of-legends.py`, `leagueinstaller_code.py` and the `python_src` folder to your instalation folder replacing all files/folders.

after that navigate to the `python_src`>`src` and copy `launch-script.py` to the main folder replacing the old file

**Comment by kassindornelles** [comment]
Tested it myself with OBS gamecapture and it captures league properly, closing.
