### ISSUE TITLE
[Feature Request] Make the installer flatpak 

### ISSUE THREAD

**Issue by tazihad** [kassindornelles/lol-for-linux-installer#45]
Can you port this scripts to work with flatpak? So, that we can directly install from flathub. Without going through all dependencies.

**Comment by kassindornelles** [comment]
> Can you port this scripts to work with flatpak? So, that we can directly install from flathub. Without going through all dependencies.

that's the next step
but for now if you are using arch linux (or a distro based on arch linux like manjaro or endeavorOS) you can use the pkgbuild

**Comment by kassindornelles** [comment]
closing since it is noted as one of the goals in the readme since ever.
