### ISSUE TITLE
Your session has expired. Please log in again to continue.

### ISSUE THREAD

**Issue by daglaroglou** [kassindornelles/lol-for-linux-installer#47]
i get that message on leagueclientux.exe randomly... it forces me to close all wine processes and relaunch it... what could cause that?
![Screenshot from 2023-05-20 15-02-57](https://github.com/kassindornelles/lol-for-linux-installer/assets/70488503/0de40d85-98e8-4713-9e93-3d5ef6d6b834)

**Comment by kassindornelles** [comment]
That's a interesting one, never happened to me 
Are you using a shared account? maybe someone else tried to login while you are logged on your PC

**Comment by daglaroglou** [comment]
nope its just me in the account... it doesnt happen on windows... idk whats wrong but using lutris has same result...

**Comment by daglaroglou** [comment]
im using v2.2 if that helps you... should i uninstall and try v2.1?

**Comment by kassindornelles** [comment]
no idea

**Comment by daglaroglou** [comment]
:|

**Comment by kassindornelles** [comment]
i can't do anything about a problem i can't reproduce, sorry

**Comment by daglaroglou** [comment]
it seems like 1st window enters idle mode or something

**Comment by daglaroglou** [comment]
yep, noticed that if i keep the window 1 busy it doesnt throw that error... any idea on how to give it priority to keep it alive?

**Comment by kassindornelles** [comment]
> yep, noticed that if i keep the window 1 busy it doesnt throw that error... any idea on how to give it priority to keep it alive?

if the client isnt being used for a long time you get disconnected in any platform i suppose?
i may be just saying bs but i witnessed such thing before after letting the game open for a while
theres nothing i can do about it still, wont be making hacks to keep it active

**Comment by daglaroglou** [comment]
not hacks... some people dont even face that thing... ill try to keep one window on desktop 1 and 2nd on desktop 2 and see if it works

**Comment by kassindornelles** [comment]
you could try using a older wine build i suppose
https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-8-LoL

**Comment by daglaroglou** [comment]
yep thats what i was told as well... i tried while using lutris but still same issue...

**Comment by kassindornelles** [comment]
> yep thats what i was told as well... i tried while using lutris but still same issue...

can you try `sudo systemctl enable --now systemd-resolved` and reboot the session?
might be DNS related even, i dont know really is just random guesses

**Comment by daglaroglou** [comment]
i tried setting DNS to `8.8.8.8` or even `1.1.1.1` but keeps happenening... also [this build](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-8-LoL) doesnt work at all, it shows up "Riot Games" logo and shows the app running on tray but after 3-5s it gets terminated

**Comment by kassindornelles** [comment]
what distribution are you using?

**Comment by daglaroglou** [comment]
Manjaro

**Comment by kassindornelles** [comment]
> i tried setting DNS to `8.8.8.8` or even `1.1.1.1` but keeps happenening... also [this build](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-8-LoL) doesnt work at all, it shows up "Riot Games" logo and shows the app running on tray but after 3-5s it gets terminated

Install dxvk, every time you update the wine build you need to reinstall it, otherwise the client won't be able to render and will crash

**Comment by kassindornelles** [comment]
> i tried setting DNS to `8.8.8.8` or even `1.1.1.1` but keeps happenening... also [this build](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-8-LoL) doesnt work at all, it shows up "Riot Games" logo and shows the app running on tray but after 3-5s it gets terminated

Install dxvk, every time you update the wine build you need to reinstall it, otherwise the client won't be able to render and will crash
