### ISSUE TITLE
[Gamemod Is Not Installed]

### ISSUE THREAD

**Issue by hofferman** [kassindornelles/lol-for-linux-installer#48]
Hey guys,

First forgive me for my English, as it is not my native language.

When I run the program I select the folder and apparently everything is fine, but then on the screen to start the launcher I get the message in red "Gamemod is not installed". What exactly am I supposed to do at this point?

If you select the "start" or "Apply Chyanges" option, nothing happens.

![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/39969679/b041cee4-4a10-48f2-acd1-f3bf55dbdbc0)

**Comment by kassindornelles** [comment]
try to disable the nvidia hybrid graphics settings, and install a older dxvk, that might help

**Comment by kassindornelles** [comment]
important to say too that when you are in the installation process of the game you have to press install in the league of legends windows that appears, otherwise we have no executable to launch later

**Comment by kassindornelles** [comment]
> "Gamemod is not installed"
that's because we dont install gamemode by ourselves, you need to install it on your distribution

are you using PopOS? if you are just go to a terminal and install it like `sudo apt install gamemode`

**Comment by kassindornelles** [comment]
another question i have for you, did you upgrade it from a older version of lol-for-linux-installer? 

theres a warning in the release page for the latest version that says:
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/40970965/3e51c339-60eb-45a8-bebf-6108cf845983)

**Comment by kassindornelles** [comment]
nvm, it is actually broken when i tried on ubuntu, zzzz, will debug it sorry for that

**Comment by hofferman** [comment]
Hello, I'm using Pop OS 22.04.

It doesn't even open the lol launcher, it just stays in the image I sent the previous print.

Anyway, thanks a lot for the help!

**Comment by hofferman** [comment]
> > "Gamemod is not installed"
> 
> that's because we dont install gamemode by ourselves, you need to install it on your distribution are you using PopOS? if you are just go to a terminal and install it like `sudo apt install gamemode`

As for that, I installed the gamemod and the message in red no longer appears.
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/39969679/c13bfdfd-46f5-4026-adb9-a8652935f548)

**Comment by kassindornelles** [comment]
can you launch the game now?
i think i found the issue in the installer code that i forgot to update to the new code

**Comment by hofferman** [comment]
> você pode iniciar o jogo agora? acho que encontrei o problema no código do instalador que esqueci de atualizar para o novo código
Sorry for my ignorance, but do I need to uninstall the program and install it again before testing?

Caso não, não deu certo

**Comment by kassindornelles** [comment]
naao, eu preciso arrumar um bug aq q passou despercebido, ja ja te retorno

**Comment by hofferman** [comment]
> naao, eu preciso arrumar um bug aq q passou despercebido, ja ja te retorno

Ok, thank you!

**Comment by kassindornelles** [comment]
resolvi meu nobre, tu usa ubuntu ou distro baseada no ubuntu?

**Comment by hofferman** [comment]
> resolvi meu nobre, tu usa ubuntu ou distro baseada no ubuntu?

I'm using pop os 22.04

**Comment by kassindornelles** [comment]
> 

https://github.com/kassindornelles/lol-for-linux-installer/releases/download/v.2.3.2/lol-for-linux-installer_2.3.2-1_amd64.deb
ve se essa build resolve pra tu menor, pra mim funcionou na maquina virtual

**Comment by kassindornelles** [comment]
vai ter que reinstalar só, mas é isso, testei e ta funcionando, foi mal ai
https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v.2.3.2

**Comment by hofferman** [comment]
Caramba, eu aqui sofrendo com meu inglês e só percebi agora que você fala portugues kkkkk'.

Então, reisntalei aqui a principio até abriu uuma tela baixando alguns pacotes do lol, porém depois disso fechou e não abriu mais nada. Agora quando clico em Start ele fecha e depois abre novamente o Launcher Manager

**Comment by kassindornelles** [comment]
instala o dxvk e ai tenta abrir de novo, eu nao instalo o dxvk por padrao, vou fazer isso numa release futura

**Comment by kassindornelles** [comment]
sem instalar o dxvk eu nao consigo abrir nem essa janela aqui kkkk 
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/40970965/1e71aa91-9431-4f04-9d4b-0fd5bf3016af)

**Comment by hofferman** [comment]
Vou dar uma pesquisada aqui de como instalar o dxvk, nunca mexi com jogos em linux

**Comment by kassindornelles** [comment]
> Vou dar uma pesquisada aqui de como instalar o dxvk, nunca mexi com jogos em linux

é assim ó 
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/40970965/4e2213a1-0382-46f1-a062-cf434aeeabca)

**Comment by kassindornelles** [comment]
se tua placa for mt antiga e nao rodar vulkan moderno instala o 1.10.3, mas tua placa de video tem que suportar vulkan ok?

**Comment by hofferman** [comment]
Ah sim, pensei que era por fora do console kkkk'

Então, tentei todas as versões, porém mesma coisa. Você tem algum discord ou algo assim? ai consigo te mostrar melhor compartilhando tela

**Comment by kassindornelles** [comment]
kassin#2888

**Comment by hofferman** [comment]
Te mandei o invite para amizade

**Comment by kassindornelles** [comment]
Closing, with a discussion with the user via discord we figure out a fix and its already merged into a new release (v.2.3.3)
