### ISSUE TITLE
My PC blow up and I can't work on this anymore 

### ISSUE THREAD

**Issue by kassindornelles** [kassindornelles/lol-for-linux-installer#51]
Development will cease since i simply can't work on this anymore and I have no source of income to acquire new hardware plus other medical bills I have, anyone wanting to fork and maintain be my guest.

**Comment by daglaroglou** [comment]
i could try working on it but i think its already in a stable and working level

**Comment by kassindornelles** [comment]
I managed to talk with AMD about my CPU damage and they accepted to recycle it and send me a new one, the problem is that my motherboard died in a power surge caused by cyclone, we'll see what happens in the next few weeks.

**Comment by daglaroglou** [comment]
cool, hope the best!

**Comment by kassindornelles** [comment]
we are back
