### ISSUE TITLE
LeagueClient.exe crash

### ISSUE THREAD

**Issue by mcnuggetsx20** [kassindornelles/lol-for-linux-installer#53]
**Describe the bug**
When I start the game from the launcher I get the error showed in the screenshot. Then it takes me back to the riot client which runs just fine

I made sure I installed every single dependency.

**Screenshots**
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/71185521/e1b0db71-11f5-44ba-98fb-42c0190d26e6)

![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/71185521/9aea53ab-863d-4b87-9db4-154316c465d7)

**Desktop (please complete the following information):**
 - Linux Distribution: Arch Linux 6.4.2-arch1-1
 - Version of the installer: 2.5.1-1

**Additional context**
The crash occurs on my laptop which is a Lenovo Thinkpad X220. The game does not crash on my main computer.

**Comment by kassindornelles** [comment]
Because Intel vulkan drivers are absolute garbage and they don't care enough to fix it, there's nothing I can do about it, sorry
