### ISSUE TITLE
[Bug] Client / Game won't open

### ISSUE THREAD

**Issue by ploonyplane** [kassindornelles/lol-for-linux-installer#54]
**Describe the bug**

**Are you sure you installed ALL the dependencies listed in the readme?**
- [x] Yes
- [ ] Not sure

**To Reproduce**
1 -  Open lol-for-linux
2 -  Hit Start League of Legends
3 -  Log in

**Describe your problem as detailed as possible**
I had expected the game to open normally after installing, but for some reason the game just crashed. I have a log I will share at the bottom if this ticket.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Linux Distribution: Arch
 - Version of the installer: 2.5.1

**Additional context**
Recent League update happened adding some stuff and changing the client slightly I believe. Could have impacted this, I am uncertain.
[crashlog.txt](https://github.com/kassindornelles/lol-for-linux-installer/files/12188940/crashlog.txt)

**Comment by kassindornelles** [comment]
Hey, I need some more information like:

- Linux distribution in usezl

**Comment by ploonyplane** [comment]
> Hey, I need some more information like:
> 
> ~Linux distribution in use~
> 
>     * GPU being used
> 
>     * driver being used (radv, NVK, ANV, Nvidia) and the driver version

Sure, I am using an RTX 2070, and the driver version is the most recent 535.86.05 .

**Comment by kassindornelles** [comment]
> > Hey, I need some more information like:
> > ~Linux distribution in use~
> > ```
> > * GPU being used
> > 
> > * driver being used (radv, NVK, ANV, Nvidia) and the driver version
> > ```
> 
> Sure, I am using an RTX 2070, and the driver version is the most recent 535.86.05 .

can you try changing the DXVK version? 
i dont see anything important in your log file

**Comment by kassindornelles** [comment]
can you try this release? <https://github.com/kassindornelles/lol-for-linux-installer/releases/download/v.2.5.5/lol-for-linux-installer-2.5.5-2-x86_64.pkg.tar.zst>
just do `sudo pacman -U lol-for-linux-installer-2.5.5-2-x86_64.pkg.tar.zst` 

preferably a clear install, hit uninstall in the current version you have and reinstall from scratch with the new version

Please let me know if it fixes it or close the issue if you are abandoning it, its no problem!

**Comment by ploonyplane** [comment]
This release functioned, however, came with an odd caveat that sometimes the game goes fully black and freezes. I can't seem to reproduce this, so I will attempt to swap the Nvidia proprietary drivers over to the open source ones and perhaps that will help.
