### ISSUE TITLE
[Bug] Installing version 2.5.6 doesn't create the script in /bin

### ISSUE THREAD

**Issue by mcnuggetsx20** [kassindornelles/lol-for-linux-installer#57]
**Describe the bug**
I updated to the latest version from 2.5.1 and the lol-for-linux-installer.py script wasn't created in /bin. I've worked this out by copying the script manually from the older version on github. After that everything works fine and I can clearly see the effect of the update. League Client finally works smoothly!

**Are you sure you installed ALL the dependencies listed in the readme?**
- Yes

**Desktop (please complete the following information):**
Arch Linux 6.4.9-arch1-1

**Comment by kassindornelles** [comment]
i fixed the pkgbuild  file (not the git one) and updated the pkg.tar file in the 2.5.6 release, can you remove the file from .bin and try to reinstall with the new package to confirm its fixed?

**Comment by kassindornelles** [comment]
PKGBUILD should be fixed now: https://github.com/kassindornelles/lol-for-linux-installer-packages/blob/main/archlinux/PKGBUILD

pkg.tar release is also fixed:  https://github.com/kassindornelles/lol-for-linux-installer/releases/download/v.2.5.6/lol-for-linux-installer-2.5.6-1-x86_64.pkg.tar.zst

**Comment by kassindornelles** [comment]
closing as i reproduced and fixed on my end too.
