### ISSUE TITLE
[Bug]  Not launching

### ISSUE THREAD

**Issue by daglaroglou** [kassindornelles/lol-for-linux-installer#60]
**Describe the bug**

**Are you sure you installed ALL the dependencies listed in the readme?**
- [x] Yes
- [ ] Not sure

**To Reproduce**
1 -  download arch package
2 - install via pacman
3 - launch it

riot launcher shows up on tray but it doesnt open any windows

CPU: i5 11600K
GPU: GTX 1660 Super
RAM: 32GB
Distro: Garuda OS

**Comment by kassindornelles** [comment]
Try installing dxvk manually in the management tab, maybe that will fix it
