### ISSUE TITLE
[BUG][PT-BR] Pós game demora vários minutos para carregar

### ISSUE THREAD

**Issue by jpalaro** [kassindornelles/lol-for-linux-installer#61]
Instalei a versão 2.5.6 nesta semana após formatar meu linux. O jogo roda bem e tudo mais. Contudo, após o término de uma partida, independente se é PvP ou Modo Treino, ao voltar para o cliente e pós game simplesmente não carrega, fica vários minutos pensando até o cliente voltar ao normal. Eu não lembro qual versão eu usava antes de formatar, mas realmente não tinha esse bug. No momento, se eu quero jogar mais de uma partida eu simplesmente mato todos os processos e lanço novamente o game.
Estou usando o Linux Mint 21.2.

**Comment by kassindornelles** [comment]
Estamos usando uma nova build, eu e algumas outras pessoas não somos afetados por esse bug na nova build, eu acho que talvez seja um problema do linux mint usar uma base muito antiga e ser problematico

**Comment by jpalaro** [comment]
Entendo, você usa o Arch ou Ubuntu?
Vou tentar instalar as versões anteriores pra encontrar a que tava mais certinha pro Mint, aí eu compartilho aqui qual é.

**Comment by kassindornelles** [comment]
> Entendo, você usa o Arch ou Ubuntu? Vou tentar instalar as versões anteriores pra encontrar a que tava mais certinha pro Mint, aí eu compartilho aqui qual é.

eu uso Arch

**Comment by jpalaro** [comment]
Opa achei a versão que está funcionando sem BUGs no Linux Mint 21.2: é uma TAG sua do começo do ano [v1.5
](https://github.com/kassindornelles/lol-for-linux-installer/tree/v1.5)
O único problema é que após instalar o ./launch-league-of-legends.py tem um pequeno erro de sintaxe, a linha `WINEESYNC="1"` tem um ponto ao invés da vírgula, então só corrigindo isso o programa funciona normal.
Enfim, essa versão funciona perfeito aqui.

**Comment by kassindornelles** [comment]
> Opa achei a versão que está funcionando sem BUGs no Linux Mint 21.2: é uma TAG sua do começo do ano [v1.5 ](https://github.com/kassindornelles/lol-for-linux-installer/tree/v1.5) O único problema é que após instalar o ./launch-league-of-legends.py tem um pequeno erro de sintaxe, a linha `WINEESYNC="1"` tem um ponto ao invés da vírgula, então só corrigindo isso o programa funciona normal. Enfim, essa versão funciona perfeito aqui.

O problema foi corrigido na main branch, agora eu tenho um sistema de seleção de versão do Wine, você pode utilizar a mesma versão do wine que utilizava na tag v.1.5 em uma tag mais atual quando eu lançar uma nova versão.

![Screenshot_20230831_180003](https://github.com/kassindornelles/lol-for-linux-installer/assets/40970965/c443cd97-90e0-4d60-9f48-ccbfc0e6843c)

**Comment by jpalaro** [comment]
s

**Comment by jpalaro** [comment]
legal vou testar.
