### ISSUE TITLE
[Bug] .deb cannot be installed on Ubuntu 23.04

### ISSUE THREAD

**Issue by Tsubajashi** [kassindornelles/lol-for-linux-installer#64]
**Describe the bug**

**Are you sure you installed ALL the dependencies listed in the readme?**
- [ ] Yes
- [X] Not sure

**To Reproduce**
1 - Install Ubuntu 23.04 
2 - Install all depends as much as possible
3 - install lol-for-linux-installer

**Describe your problem as detailed as possible**
When trying to install lol-for-linux-installer, the installer stops since it cannot find libldap-2.5-0 and libldap-2.5-0:i386.
The only packages containing libldap in name are:
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/21346945/31f46e6c-b707-4d73-a9fb-942926fb29c6)

**Screenshots**
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/21346945/9c76439d-0f02-4a13-b0e2-001e366f70a5)

**Desktop (please complete the following information):**
 - Linux Distribution: Ubuntu 23.04 
 - Version of the installer: 2.5.6-1

**Additional context**
the only thing i can think of why it wouldnt work, is that ubuntu potentially changed the naming-scheme of libldap. Could also be because its not an LTS release. For that, my knowledge on Ubuntu is not strong enough. I'm reporting for a friend who doesnt want to use any other distro. If there are any further questions, im happy to provide more help, i just need pointers what could be needed.

**Comment by kassindornelles** [comment]
yeah might be the dependency name, i'm gonna get two ubuntu virtual machines running (one LTS and the other latest ubuntu) and see what's happening, thank you for reporting the issue, i might return with news soon

**Comment by Tsubajashi** [comment]
thank you! :)

**Comment by kassindornelles** [comment]
the packages have different names, but looks like the python version on 23.04 breaks the application too, i'm not sure when i'm gonna be able to fix this :/

**Comment by kassindornelles** [comment]
For now i'm gonna add a warning in the latest release and in the readme about distro support.

Also will inform Ubuntu 23.04 is known to be broken.

**Comment by Tsubajashi** [comment]
glad you took a look at it.

**Comment by kassindornelles** [comment]
Can't promise a fix since i have other stuff going on and supporting non-LTS Ubuntu is kinda out of the scope right now, will add the tag "help wanted" to see if someone with the same issue can help me with this one

**Comment by kassindornelles** [comment]
Ok, while fixing other bug i think i figure what is happening on ubuntu 23.04, i might have a fix soon :tm:

**Comment by kassindornelles** [comment]
Can your friend try to install wine-staging following this tutorial and then try this deb file? [lol-for-linux-installer_2.5.7-1_amd64.zip](https://github.com/kassindornelles/lol-for-linux-installer/files/12491473/lol-for-linux-installer_2.5.7-1_amd64.zip)

**Comment by Tsubajashi** [comment]
i will let him know, will probably be tested in 1-2 days.

**Comment by kassindornelles** [comment]
i didnt have success with it in a virtual machine, but since is a virtual machine it might break because theres no GPU acceleration, might still be worth a try

ubuntu dropped a bunch of 32 bit dll's so this is a big problem if i want to support the next LTS in a year

**Comment by Tsubajashi** [comment]
since my friend didnt respond, i tested in a virtual machine. the install itself has gone through, but i cant verify if getting the game to work, actually works.

**Comment by kassindornelles** [comment]
it might work now on modern ubuntu versions with the latest release, we are making a special .deb package for Ubuntu 23.10 now 

https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v.2.6.5

Follow the guide in the release page/readme:

## Ubuntu 23.10 support
On Ubuntu 23.10 you need to enable i386 support:
- Download the package called `lol-for-linux-installer-ubuntu-23-10_2.6.5-1_amd64.deb`
- Run first: `sudo dpkg --add-architecture i386`
- And then `sudo apt update`
-  And finally install the .deb package use `gdebi` or other method.
