### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by alperokur** [kassindornelles/lol-for-linux-installer#66]
**Describe the bug**
OpenGL Renderer windows

**Are you sure you installed ALL the dependencies listed in the readme?**
- [x] Yes
- [ ] Not sure

**To Reproduce**
1 - 
2 - 
3 - 

**Describe your problem as detailed as possible**
Hello, when I try to run the game, OpenGL Renderer windows appear on the dash to dock before the launcher screen appears. Is there any way to prevent these? Like not appearing on Dash to Dock.

**Screenshots**
![Ekran Görüntüsü - 2023-09-14 21-33-05](https://github.com/kassindornelles/lol-for-linux-installer/assets/36308747/267b5662-c0f3-4ef2-a97b-a46981fab910)
![Ekran Görüntüsü - 2023-09-14 21-33-16](https://github.com/kassindornelles/lol-for-linux-installer/assets/36308747/435c9449-609f-4eac-b7d2-65efff5ee377)

**Desktop (please complete the following information):**
 - Linux Distribution: Ubuntu 23.04 (new setup)
 - Version of the installer: Latest (v2.5.7)

**Additional context**

**Comment by kassindornelles** [comment]
Nothing i can do about that, but you can use an older WINE build to get rid of those, you are going to miss some performance on the client tho, use the wine build selector and select wineLutrisGE7 
![image](https://github.com/kassindornelles/lol-for-linux-installer/assets/40970965/42a55d29-d0a0-49b3-b273-397e34cf68df)
