### ISSUE TITLE
fps locked at 60[Bug] 

### ISSUE THREAD

**Issue by pedroborraz** [kassindornelles/lol-for-linux-installer#67]
**Describe the bug**

Game when in focus, locked at 60 fps even without fps limit. But in the background activity panel it unlocks the fps

**Are you sure you installed ALL the dependencies listed in the readme?**
- [x] Yes
- [ ] Not sure

**To Reproduce**
1 - install the game
2 - launch

**Describe your problem as detailed as possible**

my notebook has the capacity to run the game above 60 fps, as it has a limit the game shows some drops below 60 fps quickly

**Desktop (please complete the following information):**
 - Linux Distribution: Fedora 38
 - Wayland
 -  Linux Kernel: 6.5.8-200
 - DE: Gnome
 - CPU: i5-8265U
 - GPU: GeForce MX130
 - RAM: 8 GB
 - Version of the installer: [2.6.3](https://github.com/kassindornelles/lol-for-linux-installer/releases/tag/v.2.6.3)

**Additional context**
probably something related to wine.

**Comment by kassindornelles** [comment]
This is a nvidia or gnome issue, nothing i can do about it

**Comment by kassindornelles** [comment]
NVIDIA is not supported, but, you can try to use a older wine build using the selector in the Management tab.
