### ISSUE TITLE
[Suggestion] Use Haze's League RPC

### ISSUE THREAD

**Issue by GinjuGG** [kassindornelles/lol-for-linux-installer#72]
Use [Its-Haze](https://github.com/Its-Haze/league-rpc-linux/commits?author=Its-Haze)'s League RPC Fork https://github.com/Its-Haze/league-rpc-linux

It's a fork from [daglaroglou](https://github.com/daglaroglou/league-rpc-linux/commits?author=daglaroglou) but with more recent updates and features.

**Comment by GinjuGG** [comment]
He added a League RPC Launchscript
https://github.com/Its-Haze/league-rpc-linux/blob/master/league-rpc-auto-launcher.sh

**Comment by kassindornelles** [comment]
Oh wow, thats interesting, i will take a look

**Comment by kassindornelles** [comment]
You should be able to test it now with the main branch https://github.com/kassindornelles/lol-for-linux-installer/commit/2e3dfb8b2a5aa28ebcc9b5a68537f6dfb1548f75
